server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdatabase?characterEncoding=utf8mb4$useSSL=true
    name: root
    password: 123456

#字符串
string:
 value: hello

#布尔值
boolean.value1: true
boolean.value2: false

#整数
int.value: 10
int.value1: 0b1010_0111_0100_1010_1110

#浮点数
float.value: 3.14159
float.value2: 314159e-5

#Null,~代表null
null.value: ~


student1:
  id: 1
  name: 张三
  age: 18

student2: {id: 2,name: 李四,age: 20}


alist1:
  name:
    - mysql
    - java
    - sqlserver

alist2: {name: [mysql,java,sqlserver]}

